### ISSUE TITLE
Feature request: Add shortcut keys for autocomplete 

### ISSUE THREAD

**Issue by duytrung** [Zinggi/DictionaryAutoComplete#23]
Hi Zinggi,

I like this plugin very much.

Could you implement a fuzzy word completion such let us dont have to type "Complete" instead it show:
1.  "ComPlete" (pressing "P" to complete") or "CompletE" -> pressing E to enter "Complete" or
2. "Complete" -----> 1 (Press 1 to choose)
    "Completed" ----> 2
    "Completely" ----> 3 (Press 3 to choose, etc) or
===> show a list of 10 item from 0 to 94
3. "Complete" -----> a (Press a to choose, any letter that does not exist in "complete")
    "Completed" ----> b
    "Completely" ----> d (Press d to choose, etc) or
===> show a list of a to z of item of completion
I think that this add extra speed for the typing.
Any idea?

Thanks!

**Comment by Zinggi** [comment]
Hi Trung,

I'm not actively developing this package anymore. Unfortunately I just don't have the time.

<br/>
Regarding your suggestion, if you like, you can implement it yourself and send me a pull request.

If you do, make sure it's configurable in the settings, so that people can optionally turn it on. (off by default, as I think this is a too intrusive change)

Thanks for understanding

**Comment by kpym** [comment]
This is not possible, because the way Sublime treats auto-completions. It ask the plugin for a list of suggestions and then it manage them. We can't decide how Sublime will treat the suggestion list.

**Comment by kpym** [comment]
In  962e3f9 a new setting `numeric shortcuts` was added. When set to `true` it changes the way auto complete behaves: all the choices are numbered and pressing a number select the corresponding completion. 

If you use this setting you should probably set `maximum results` to less than 10.
